apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
  namespace: godoc
  labels:
    name: server
    role: web
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: server
      labels:
        name: server
        role: web
    spec:
      imagePullSecrets:
     - name: wantedlybotkey
      containers:
      - image: quay.io/wantedly/docker-godoc:latest
        name: server
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: redis://redis:6379
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: github-token
