apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
  namespace: godoc
  labels:
    name: server
    role: web
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: server
      labels:
        name: server
        role: web
    spec:
      containers:
      - image: quay.io/wantedly/godoc:latest
        name: server
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: redis://redis:6379
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: github-token
      - image: quay.io/dtan4/nginx-basic-auth-proxy
        name: nginx-basic-auth-proxy
        ports:
        - containerPort: 8081
        env:
        - name: BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: nginx-basic-auth-username
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: nginx-basic-auth-password
        - name: PROXY_PASS
          value: http://localhost:8080/
        - name: PORT
          value: "8081"
        - name: SERVER_NAME
          value: godoc.wantedly.com
